### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by Kazuma-Feb** [v3921358/ZLHSS079#1]
fixed

**Comment by v3921358** [comment]
<imgdir name="2311003">
		<string name="name" value="神圣祈祷"/>
		<string name="desc" value="[最高等级:30]\n组队时候,能得到更多经验值。只有两个人以上的组队状态下才能发挥100%效果。\n必需技能 : #c净化等级3以上#"/>

**Comment by shotaro7906** [comment]
啊 明白了 抱歉。 應該是沒組隊的原因

1.不過爆率問題請問是什麼情況呀 QQ
2.然後還有個問題 因為老是卡號 但是gui的解卡似乎不能使用 
我看到別的源碼有可以頂號的設置 但是不知道是修改哪裡 宗達大大是否能指路看看呢?
3.最後就是似乎有一些小BUG 但是不清楚原因 1個是情侶之間的愛心特效一旦出現 及時A和B不在一個地圖 依舊頭上會有愛心顯示(儘本人可見) / 只帶了一只寵物(貓咪/品克繽) 自己看不到群寵特效 但其他人會看到群寵特效(叢林/一堆食物的群寵特效) 很奇怪 :(

再次感謝宗達大大的回復 謝謝!()

**Comment by v3921358** [comment]
666fb83cfc2b63617dc49b64ddf8604f2b8d3cdf
卡號問題

**Comment by v3921358** [comment]
fd6858bb9e94056e82385061eb6cc54ab3fe3f29
掉落機率問題

**Comment by v3921358** [comment]
02c39e5a8ecb6170994db4c9fdf46669916e5bc4
戒指問題

**Comment by v3921358** [comment]
d52a932855621a0972042e7df45789f9eff4be00
寵物特效問題，沒測試

**Comment by shotaro7906** [comment]
![F%NFOL_EL7WLM)_@B`A4FQK](https://user-images.githubusercontent.com/77085333/103860390-70657f00-50b3-11eb-9309-35f70322f8a0.png)

**Comment by shotaro7906** [comment]
大大 安安！

感謝回復 實在是感激， 我也就趕緊測試了下

裝備已經明白
寵物我也沒測試 單機也找不到人而且也沒法多開哈哈哈
卡號問題也沒測試 但是應該是OK的！！

戒指的話依舊是有問題 比較特殊的是
1.上線不帶 結婚戒指 （非戀人戒指）頭上是不會有愛心的 但是但凡戴上了 即使摘下來 依舊是會有這個effect在， 很奇怪。

其餘感覺都很好 然後想問一下 消耗品的slotmax是根據什麼進行反應呢
首先WZ裡不是每個消耗品都有slotmax的樣子？ 數據庫的Slotmax我也進行更改過 但是並沒生效成果
我開始以為是GM指令會有[XX 直接製作了 XXX] 的原因 後來通過DROP指令 或者是商店購買依舊是 100是slotMax
難道是客戶端有限制嗎？？ （暫時沒有找到別的客戶端maplestory替代 晚點會進行測試）

總之還是很感謝 宗達大大 端非常優秀！！ 體驗很好！回憶復古

我自己有把 神聖祈禱的 /500 改為 /100 更適合單人體驗 並且自己也改了一下 出生的秘密箱子送的道具什麼的哈哈哈 感覺這個過程很有意思 :D !!!

**Comment by v3921358** [comment]
slotMax現在是讀取服務端xml裡面的，除了裝備都是一，其他道具沒有寫入代表都是100，
可以在函數getSlotMax中進行修改

**Comment by v3921358** [comment]
結婚戒指的話代碼給我，我再去看下

**Comment by Kazuma-Feb** [comment]
1112804 這個是結婚戒指的代碼

**Comment by v3921358** [comment]
是用商城送禮獲得的戒指嗎?

**Comment by shotaro7906** [comment]
不是 這個戒指是 當我與對方參加婚禮後自動雙方會獲取的一個戒指

**Comment by shotaro7906** [comment]
組隊去射手村 一個和尚進去 然後參加中式婚禮什麼的

**Comment by shotaro7906** [comment]
我本來懷疑是不是是 seteffect 單件 但是想想脫下來效果還在 也就不明所以問題點了

**Comment by v3921358** [comment]
正常來說的話，結婚完，雙方同張地圖，頭上就應該要一直有這特效的，不論戒指是否穿戴

**Comment by shotaro7906** [comment]
現在的情況是只有我一個人在線 也只有我一個人在地圖 帶上戒指就有特效 並且脫掉以後戒指的特效也依舊存在 很奇怪 估計很迷惑了

**Comment by shotaro7906** [comment]
![QQ图片20210107164034](https://user-images.githubusercontent.com/77085333/103918887-4b026080-5107-11eb-9e95-1e9249835234.png)
![QQ图片20210107164039](https://user-images.githubusercontent.com/77085333/103918889-4b9af700-5107-11eb-9df3-9111c2fa2fce.png)

**Comment by shotaro7906** [comment]
很有意思 圖1是別人的視角看我 我一隻寵物但是有群寵的特效

圖2 是別人的視角看到 我頭上沒有結婚戒指的特效  （等於只有我自己能看到BUG）

**Comment by Kazuma-Feb** [comment]
宗達大大好

通過MapleStatEffect查看技能 爆炸箭（arrow bomb）是擁有眩暈效果的
如下：
               case 1211002: // charged blow
                case 1111008: // shout
                case 4211002: // assaulter
                case 3101005: // arrow bomb          這個就是爆炸箭 應該有眩暈
                case 1111005: // coma: sword
                case 1111006: // coma: axe
                case 4221007: // boomerang step
                case 5101002: // Backspin Blow
                case 5101003: // Double Uppercut
                case 5121004: // Demolition
                case 5121005: // Snatch
                case 5121007: // Barrage
                case 5201004: // pirate blank shot
                case 4121008: // Ninja Storm
                case 22151001:
                case 4201004: //steal, new
                case 33101001:
                case 33101002:
                case 32111010:
                case 32121004:
                case 33111002:
                case 33121002:
                case 35101003:
                case 35111015:
                case 5111002: //energy blast
                case 15101005:
                case 4331005:
                    monsterStatus.put(MonsterStatus.眩晕, 1);
                    break;

但是在遊戲內 並不能成功眩暈怪物 很奇怪但是我無法解決。

另外想問一下，似乎數據庫的ITEM EQUIPMENT是不是沒有意義因為其效果是在XML上生效的。包括Item的數據庫 price和slotmax什麼的也是數據庫可生效。 這樣是更便利是嗎 （單純提問沒有覺得有問題）。 唯一特點是當我刪除Itemdata的部分 客戶端不存在的道具時 啟動服務端會報錯 （因為ITEM equipment有他們的屬性 哈哈哈） 所以我就把對應的item equipment屬性也刪了。

**Comment by Kazuma-Feb** [comment]
content.com/77085333/104971158-d3291580-59e5-11eb-9cc7-111365ea1a85.png)
![image](https://user-images.githubusercontent.com/77085333/104971161-d4f2d900-59e5-11eb-8033-5465068ba09a.png)

**Comment by Kazuma-Feb** [comment]
補充，怪物是有眩暈提示的 但是怪物本身並不會被眩暈。
![image](https://user-images.githubusercontent.com/77085333/104971190-ea680300-59e5-11eb-8054-136b3b3d8b92.png)

**Comment by v3921358** [comment]
#5
