### ISSUE TITLE
currenttime issue

### ISSUE THREAD

**Issue by Kazuma-Feb** [v3921358/ZLHSS079#2]
特別神奇的一點

在線時間獎勵是按照中國時間來算的
但是製作道具(10天的游泳圈 1天的經驗卡等等), 時間是按照美國時間計算的 很奇怪。 e.g. 1月2日0點製作1天道具(美國時間為1月1日11點),到期時間為1月2日11點。

嘗試尋找問題原因 找不到結果 :( 

也不知道真正道具到期時間是當中國時間11點(即1.2日11點)到期還是美國時間(1.2日11點到期)(即中國時間1.3日24點)

**Comment by Kazuma-Feb** [comment]
還有一個殺怪記錄的BUG 當切換頻道，sg會重置為0

**Comment by v3921358** [comment]
在線時間獎勵指的是哪一部分呢?

**Comment by v3921358** [comment]
殺怪記錄BUG
20553f8694e41e158472f249c52ec15d2ea37acf

**Comment by v3921358** [comment]
道具期限BUG
a807ca03496640aa20e3622563137a3a059ab76e
