### ISSUE TITLE
一进商城就黑屏

### ISSUE THREAD

**Issue by qa2080639** [v3921358/ZLHSS079#8]
游戏其他功能正常  就是进不了商城
自己编译的包和别人的wz及客户端  
是否有配套的wz和客户端呢  还有编译的配置

**Comment by v3921358** [comment]
你有導入額外放的商城表麼?
那個不導入，進商城就是黑屏
-------------------
wz那些我用的都是原版的079

**Comment by qa2080639** [comment]
导入sql就可以   感谢
