### ISSUE TITLE
安安

### ISSUE THREAD

**Issue by Kazuma-Feb** [v3921358/ZLHSS079#9]
我又來了
簡單如下 
1.非群寵狀態似乎會出現寵物不吃食物的狀況。 很奇怪
2.寵物補血方面 被怪物攻擊損失血量會補血 但是人物自主損血不會 e.g 快速武器消耗的 戰士群攻消耗的 etc. 很神奇
3.最後根據物語大佬上傳的一鍵端內的 精靈項鏈， 因為js內有判斷裝備欄是不是有空格 !1 = null 什麼的 然後才會兌換。 但是發現有時候空包他還是會說 裝備欄位置不足 :D xD

**Comment by v3921358** [comment]
不吃食物: 249c15c651ed8b2524a9f12ff465b4f7718c786e
補血的話是客戶端發送的請求，可能那種扣血不滿足請求條件
